source 'https://rubygems.org'

group :jekyll_plugins do
    #gem 'wdm', '>= 0.1.0'
    gem 'classifier-reborn'
    gem 'jekyll'
    gem 'jekyll-archives'
    gem 'jekyll-diagrams'
    gem 'jekyll-email-protect'
    gem 'jekyll-feed'
    gem 'jekyll-imagemagick'
    gem 'jekyll-link-attributes'
    gem 'jekyll-minifier'
    gem 'jekyll-paginate-v2'
    gem 'jekyll-scholar'
    gem 'jekyll-sitemap'
    gem 'jekyll-toc'
    gem 'jekyll-twitter-plugin'
    gem 'jemoji'
    gem 'mini_racer'
    gem 'unicode_utils'
    gem 'webrick'
    gem 'jekyll-sass-converter', '=3.0.0'
    gem 'mercenary',  '0.3.6'
    gem 'listen', '>=3.7'
end
group :other_plugins do
    gem 'feedjira'
    gem 'httparty'
end
